language: node_js
node_js:
  - "12"

install:
  - npm install -g serverless
  - travis_retry npm install

script:
  - serverless deploy

environments:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION}
